version: '2'

services:
  balancer:
    container_name: balancer
    build:
      context: .
      dockerfile: ./balanceWebServices/Dockerfile
    depends_on:
      - target-service01
      - target-service02
      - target-service03
      - target-service04
      - target-service05
    ports:
      - "8080:8080"
    networks:
      - installment-loc

  target-service01:
    container_name: target-service01
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile01
    ports:
      - "8081:8081"
    networks:
      - installment-loc

  target-service02:
    container_name: target-service02
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile02
      args:
        NAME: "target-service02"
        PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - installment-loc

  target-service03:
    container_name: target-service03
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile03
      args:
        NAME: "target-service03"
        PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - installment-loc

  target-service04:
    container_name: target-service04
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile04
      args:
        NAME: "target-service04"
        PORT: 8084
    ports:
      - "8084:8084"
    networks:
      - installment-loc
        
  target-service05:
    container_name: target-service05
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile05
      args:
        NAME: "target-service05"
        PORT: 8085
    ports:
      - "8085:8085"
    networks:
      - installment-loc
networks:
  installment-loc: