version: '2'

services:
  balancer:
    container_name: balancer
    build:
      context: .
      dockerfile: ./balanceWebServices/Dockerfile
    ports:
      - "8080:8080"

  target-service01:
    environment:
      - NAME="TestService01"
      - PORT=8081
    container_name: target-service01
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile01
      args:
        NAME: "TestService01"
        PORT: 8081
    ports:
      - "8081:8081"

  target-service02:
    container_name: target-service02
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile02
      args:
        NAME: "TestService02"
        PORT: 8082
    ports:
      - "8082:8082"

  target-service03:
    container_name: target-service03
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile03
      args:
        NAME: "TestService03"
        PORT: 8083
    ports:
      - "8083:8083"

  target-service04:
    container_name: target-service04
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile04
      args:
        NAME: "TestService04"
        PORT: 8084
    ports:
      - "8084:8084"
        
  target-service05:
    container_name: target-service05
    build:
      context: .
      dockerfile: ./targetWebService/DockerFiles/Dockerfile05
      args:
        NAME: "TestService05"
        PORT: 8085
    ports:
      - "8085:8085"